### ISSUE TITLE
Support body and title from action inputs

### ISSUE THREAD

**Issue by adborden** [JasonEtco/create-an-issue#90]
I'd like to have the action completely contained within the GH workflow instead of requiring a template file. This also makes it easier to refer to GitHub Action context, job, and step outputs.

**Comment by JasonEtco** [comment]
Seems reasonable to me! If you're up for it, a PR would be welcome - here's a similar addition you can look at: https://github.com/JasonEtco/create-an-issue/pull/44. Let me know if you have any questions!

**Comment by JasonEtco** [comment]
Close for inactivity. Anyone is welcome to reopen it and open a PR for it, but since no one has, I'll assume it's not a pressing request.

**Comment by saerosV** [comment]
Hey @JasonEtco.

I think this would be a really useful feature to use alongside [GitHub Reusable Workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows). 

The way this action works currently, the template files need to be added to every repository that has a caller workflow, instead of only adding it to the reusable workflow repository. Alternatively, you can do something "hacky" [like this](https://github.com/orgs/community/discussions/27201#discussioncomment-3254986).

The proposed feature would solve this problem completely.

I would be willing to work on a PR for this, but at the moment I'm not sure about a time frame for it to be finished

For future reference, the [issue-bot action](https://github.com/imjohnbo/issue-bot) could serve as a reference on how to implement this feature.
